# Generated by Django 4.0.5 on 2022-07-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_isnormaluser_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isAdminUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
    ]
