# Generated by Django 4.0.5 on 2022-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'superadmin'), (2, 'admin'), (3, 'normaluser')], default=3, null=True),
        ),
    ]
